# Generated by Django 5.2.16 on 2026-07-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0001_initial'),
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.CharField(blank=True, default='', max_length=40)),
                ('folio', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('origen', models.CharField(choices=[('webhook', 'Webhook'), ('reconciliacion', 'Reconciliación'), ('manual', 'Manual')], default='webhook', max_length=15)),
                ('comprador_nombre', models.CharField(blank=True, max_length=120)),
                ('comprador_tel', models.CharField(blank=True, max_length=20)),
                ('comprador_email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.JSONField(blank=True, default=dict)),
                ('cp', models.CharField(blank=True, max_length=10, verbose_name='código postal')),
                ('es_local', models.BooleanField(default=False, help_text='CP de Colima (28xxx): entrega local propia')),
                ('valor_declarado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nota_regalo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PICKING', 'En picking'), ('EMPACADO', 'Empacado'), ('GUIA_GENERADA', 'Guía generada'), ('RECOLECTADO', 'Recolectado'), ('EN_TRANSITO', 'En tránsito'), ('ENTREGADO', 'Entregado'), ('ENTREGA_PRESUNTA', 'Entrega presunta'), ('PARCIALMENTE_DESPACHADO', 'Parcialmente despachado'), ('CANCELACION_PENDIENTE', 'Cancelación pendiente'), ('CANCELADO', 'Cancelado'), ('RETORNADO', 'Retornado')], db_index=True, default='PENDIENTE', max_length=30)),
                ('corte_vigente_al_ingreso', models.TimeField(blank=True, help_text='Corte contractual vigente al ingerir: evidencia auditable del SLA de salida', null=True)),
                ('ts_picking', models.DateTimeField(blank=True, null=True)),
                ('ts_empacado', models.DateTimeField(blank=True, null=True)),
                ('ts_guia', models.DateTimeField(blank=True, null=True)),
                ('ts_recolectado', models.DateTimeField(blank=True, null=True)),
                ('ts_en_transito', models.DateTimeField(blank=True, null=True)),
                ('ts_entregado', models.DateTimeField(blank=True, null=True)),
                ('incidencia_activa', models.BooleanField(default=False)),
                ('peso_esperado_gr', models.PositiveIntegerField(default=0)),
                ('peso_real_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
                ('tienda', models.ForeignKey(blank=True, help_text='Vacío solo para pedidos manuales sin tienda', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='integraciones.tienda')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-creado'],
                'unique_together': {('tienda', 'shopify_order_id')},
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_pickeada', models.PositiveIntegerField(default=0)),
                ('reservada', models.BooleanField(default=False, help_text='True si inventario.reservar apartó el stock de esta línea')),
                ('lote_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_pedido', to='catalogo.lote')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_pedido', to='catalogo.sku')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'línea de pedido',
                'verbose_name_plural': 'líneas de pedido',
                'ordering': ['id'],
            },
        ),
    ]
