# Generated by Django 5.2.17 on 2026-08-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='parcial_de_orden',
            field=models.BooleanField(default=False, help_text='La orden de Shopify se dividió entre locations: este pedido ampara solo NUESTRO ticket'),
        ),
    ]
