# Generated by Django 5.2.17 on 2026-08-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_parcial_de_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='nota_kit',
            field=models.CharField(blank=True, default='', help_text='Lo que el comprador eligió (texto de Appstle), para el packer', max_length=300),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='parte_de_kit',
            field=models.ForeignKey(blank=True, help_text='Línea kit a la que pertenece este componente (té dentro de la TeaBox)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='pedidos.lineapedido'),
        ),
    ]
