# Generated by Django 5.2.17 on 2026-09-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_asignacion_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='reingreso_estado',
            field=models.CharField(blank=True, choices=[('', 'Sin decidir'), ('reingresado', 'Reingresado'), ('no_recuperado', 'Inventario no recuperado')], default='', max_length=15),
        ),
    ]
