# Generated by Django 5.2.17 on 2026-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_reingreso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cancelacion_tardia',
            field=models.BooleanField(default=False),
        ),
    ]
