# Generated by Django 5.2.17 on 2026-09-14 19:25

from django.db import migrations, models


def rellenar_canal(apps, schema_editor):
    """Pedidos existentes: canal desde el payload del último webhook de su orden
    (WebhookEvento conserva el JSON); manuales → manual; sin payload → web."""
    from apps.pedidos.services import canal_desde_payload

    Pedido = apps.get_model("pedidos", "Pedido")
    WebhookEvento = apps.get_model("integraciones", "WebhookEvento")
    Pedido.objects.filter(origen="manual").update(canal="manual")
    for pedido in Pedido.objects.exclude(origen="manual").exclude(tienda__isnull=True).iterator():
        evento = (
            WebhookEvento.objects.filter(tienda_id=pedido.tienda_id, topic__startswith="orders/")
            .filter(payload__id=int(pedido.shopify_order_id) if pedido.shopify_order_id.isdigit() else -1)
            .order_by("-ts").first()
        )
        if evento is None:
            continue
        canal, fuente = canal_desde_payload(evento.payload)
        Pedido.objects.filter(pk=pedido.pk).update(canal=canal, canal_fuente=fuente)



class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_cancelacion_tardia'),
        ('integraciones', '0002_tienda_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='canal',
            field=models.CharField(choices=[('web', 'Tienda en línea'), ('tiktok', 'TikTok Shop'), ('b2b', 'B2B'), ('pos', 'Punto de venta'), ('social', 'Redes sociales'), ('manual', 'Manual'), ('otro', 'Otro')], db_index=True, default='web', max_length=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='canal_fuente',
            field=models.CharField(blank=True, help_text='source_name crudo de Shopify', max_length=60),
        ),
        migrations.RunPython(rellenar_canal, migrations.RunPython.noop),
    ]
