# Generated by Django 5.2.17 on 2026-09-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_linea_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='shopify_fulfillment_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
