# Generated by Django 5.2.17 on 2026-09-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_shopify_fulfillment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='cantidad_despachada',
            field=models.PositiveIntegerField(default=0, help_text='Unidades que ya salieron de bodega en un manifiesto anterior'),
        ),
    ]
