# Generated by Django 5.2.17 on 2026-09-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_lineapedido_cantidad_despachada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='canal',
            field=models.CharField(choices=[('web', 'Tienda en línea'), ('tiktok', 'TikTok Shop'), ('b2b', 'B2B'), ('pos', 'Punto de venta'), ('social', 'Redes sociales'), ('suscripcion', 'Suscripción'), ('manual', 'Manual'), ('otro', 'Otro')], db_index=True, default='web', max_length=12),
        ),
    ]
