# Generated by Django 5.2.17 on 2026-09-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_pedido_canal_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_pendiente',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
