# Generated by Django 5.2.17 on 2026-09-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_pedido_direccion_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrier_forzado',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
