# Generated by Django 5.2.17 on 2026-09-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_carrier_forzado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='shopify_order_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
