# Generated by Django 5.2.17 on 2026-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_pedido_shopify_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ts_recolectado_carrier',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
