# Generated by Django 5.2.17 on 2026-09-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_recolectado_por_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='reposicion_de',
            field=models.ForeignKey(blank=True, help_text='Línea original que esta línea repone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposiciones', to='pedidos.lineapedido'),
        ),
    ]
