# Generated by Django 5.2.17 on 2026-10-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_pedido_costo_entrega_propia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detenido',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
