# Generated by Django 5.2.16 on 2026-07-22 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reposicion', 'Reposición física'), ('reembolso', 'Reembolso'), ('cupon', 'Cupón')], max_length=12)),
                ('monto', models.DecimalField(decimal_places=2, help_text='MXN', max_digits=10)),
                ('estado', models.CharField(choices=[('COTIZADA', 'Cotizada'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada')], db_index=True, default='COTIZADA', max_length=10)),
                ('aprobo', models.CharField(blank=True, max_length=120)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'compensación',
                'verbose_name_plural': 'compensaciones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=120)),
                ('rol_autor', models.CharField(choices=[('mesa', 'Mesa de Control'), ('cliente', 'Cliente'), ('comprador', 'Comprador final'), ('sistema', 'Sistema')], max_length=10)),
                ('texto', models.TextField()),
                ('interno', models.BooleanField(default=False, help_text='Nota interna: no se muestra en el portal, pero queda en el registro.')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'mensaje de incidencia',
                'verbose_name_plural': 'mensajes de incidencia',
                'ordering': ['ts'],
            },
        ),
        migrations.CreateModel(
            name='ReclamacionCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=40)),
                ('monto_reclamado', models.DecimalField(decimal_places=2, help_text='MXN', max_digits=10)),
                ('estado', models.CharField(choices=[('PREPARADA', 'Preparada'), ('PRESENTADA', 'Presentada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('PAGADA', 'Pagada')], db_index=True, default='PREPARADA', max_length=10)),
                ('monto_recuperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_presentacion', models.DateField(blank=True, null=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'reclamación a carrier',
                'verbose_name_plural': 'reclamaciones a carrier',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('DAN', 'Daño / rotura'), ('RET', 'Retraso'), ('RF', 'Retorno falso / no entregado'), ('FAL', 'Pedido incompleto'), ('DIR', 'Dirección'), ('CAN', 'Cancelación tardía'), ('DES', 'Descuadre de inventario')], max_length=3)),
                ('prioridad', models.CharField(choices=[('P1', 'P1 · crítica'), ('P2', 'P2 · normal'), ('P3', 'P3 · baja')], default='P2', max_length=2)),
                ('origen', models.CharField(choices=[('auto', 'Automática (sistema)'), ('manual', 'Manual (Mesa)'), ('comprador', 'Comprador final'), ('cliente', 'Cliente (portal)')], default='manual', max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_CURSO', 'En curso'), ('RESOLUCION_PROPUESTA', 'Resolución propuesta'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada')], db_index=True, default='ABIERTA', max_length=24)),
                ('dueno', models.CharField(blank=True, help_text='Quién tiene la pelota', max_length=120)),
                ('ts_apertura', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ts_primera_respuesta', models.DateTimeField(blank=True, null=True)),
                ('ts_resolucion', models.DateTimeField(blank=True, null=True)),
                ('ts_cierre', models.DateTimeField(blank=True, null=True)),
                ('sla_respuesta_limite', models.DateTimeField(blank=True, null=True)),
                ('sla_resolucion_limite', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='core.cliente')),
            ],
            options={
                'verbose_name': 'incidencia',
                'verbose_name_plural': 'incidencias',
                'ordering': ['-ts_apertura'],
            },
        ),
    ]
