# Generated by Django 5.2.16 on 2026-07-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('incidencias', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='catalogo.sku'),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensaciones', to='incidencias.incidencia'),
        ),
        migrations.AddField(
            model_name='mensajeincidencia',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='incidencias.incidencia'),
        ),
        migrations.AddField(
            model_name='reclamacioncarrier',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='incidencias.incidencia'),
        ),
    ]
