# Generated by Django 5.2.17 on 2026-09-11 20:32

import django.db.models.deletion
import re

from django.db import migrations, models


def ligar_des_historicas(apps, schema_editor):
    """Las DES de recepción anteriores solo mencionan el folio en su primer
    mensaje ("La recepción ASN-0004 de …"); se ligan por ese folio."""
    Incidencia = apps.get_model("incidencias", "Incidencia")
    Mensaje = apps.get_model("incidencias", "MensajeIncidencia")
    OrdenEntrada = apps.get_model("inventario", "OrdenEntrada")
    for inc in Incidencia.objects.filter(tipo="DES", orden__isnull=True):
        primero = Mensaje.objects.filter(incidencia=inc).order_by("ts", "pk").first()
        encontrado = re.search(r"La recepción (ASN-\d+)", primero.texto) if primero else None
        orden = OrdenEntrada.objects.filter(folio=encontrado.group(1)).first() if encontrado else None
        if orden is not None:
            inc.orden = orden
            inc.save(update_fields=["orden"])

class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_initial'),
        ('inventario', '0005_orden_entrada_reingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='inventario.ordenentrada'),
        ),
        migrations.RunPython(ligar_des_historicas, migrations.RunPython.noop),
    ]
