# Generated by Django 5.2.17 on 2026-09-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_cancelacion_y_cambio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='interna',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('DAN', 'Daño / rotura'), ('RET', 'Retraso'), ('RF', 'Retorno falso / no entregado'), ('FAL', 'Pedido incompleto'), ('DIR', 'Dirección'), ('CAN', 'Cancelación tardía'), ('DES', 'Descuadre de inventario'), ('CDR', 'Cambio de dirección'), ('PAQ', 'Sin paquetería que cotice')], max_length=3),
        ),
    ]
