# Generated by Django 5.2.17 on 2026-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_incidencia_interna_y_sin_paqueteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensacion',
            name='avisar_comprador',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='creada_por',
            field=models.CharField(choices=[('mesa', 'Mesa de Control'), ('cliente', 'el cliente')], default='mesa', max_length=10),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='lineas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='nota',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='reembolsar_envio',
            field=models.BooleanField(default=False),
        ),
    ]
