# Generated by Django 5.2.17 on 2026-09-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0006_compensacion_ejecucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensacion',
            name='motivo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
