# Generated by Django 5.2.17 on 2026-10-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0007_compensacion_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('DAN', 'Daño / rotura'), ('RET', 'Retraso'), ('RF', 'Retorno falso / no entregado'), ('FAL', 'Pedido incompleto'), ('DIR', 'Dirección'), ('CAN', 'Cancelación tardía'), ('DES', 'Descuadre de inventario'), ('CDR', 'Cambio de dirección'), ('PAQ', 'Sin paquetería que cotice'), ('DET', 'Detenido en piso')], max_length=3),
        ),
    ]
