# Generated by Django 5.2.17 on 2026-10-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0009_tipo_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('DAN', 'Daño / rotura'), ('RET', 'Retraso'), ('RF', 'Retorno falso / no entregado'), ('FAL', 'Pedido incompleto'), ('DIR', 'Dirección'), ('CAN', 'Cancelación tardía'), ('DES', 'Descuadre de inventario'), ('CDR', 'Cambio de dirección'), ('PAQ', 'Sin paquetería que cotice'), ('DET', 'Detenido en piso'), ('SKU', 'Producto no registrado'), ('ERR', 'Producto erróneo')], max_length=3),
        ),
    ]
