# Generated by Django 5.2.16 on 2026-07-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=40)),
                ('servicio', models.CharField(blank=True, max_length=60)),
                ('numero', models.CharField(blank=True, db_index=True, max_length=64)),
                ('costo_cotizado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_preferencial', models.DecimalField(decimal_places=2, default=0, help_text='Tasa preferencial envia.com', max_digits=10)),
                ('etiqueta_url', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('GUIA_CREADA', 'Guía creada'), ('RECOLECTADO', 'Recolectado por el carrier'), ('EN_TRANSITO', 'En tránsito'), ('EN_RUTA', 'En ruta de entrega'), ('ENTREGADO', 'Entregado'), ('INTENTO_FALLIDO', 'Intento de entrega fallido'), ('RETENIDO', 'Retenido'), ('RETORNO', 'Retorno al remitente'), ('EXCEPCION', 'Excepción')], db_index=True, default='GUIA_CREADA', max_length=20)),
                ('ultimo_evento', models.CharField(blank=True, max_length=300)),
                ('ts_ultimo_movimiento', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'guía',
                'verbose_name_plural': 'guías',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ReglaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.PositiveIntegerField(default=100, help_text='Menor número = se evalúa primero')),
                ('condicion', models.JSONField(blank=True, default=dict, help_text='{"es_local": true} / {"cp_prefijo": "28"} / {} (aplica siempre)')),
                ('carrier', models.CharField(max_length=40)),
                ('servicio', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'regla de envío',
                'verbose_name_plural': 'reglas de envío',
                'ordering': ['prioridad', 'id'],
            },
        ),
    ]
