# Generated by Django 5.2.16 on 2026-08-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_destino', models.CharField(db_index=True, max_length=5)),
                ('peso_kg', models.DecimalField(decimal_places=1, help_text='Redondeado a 0.5', max_digits=6)),
                ('carrier', models.CharField(max_length=40)),
                ('servicio', models.CharField(blank=True, max_length=60)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimado_entrega', models.CharField(blank=True, max_length=60)),
                ('ok', models.BooleanField(default=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cotización en caché',
                'verbose_name_plural': 'cotizaciones en caché',
                'unique_together': {('cp_destino', 'peso_kg', 'carrier')},
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='1..N dentro del pedido')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largo_cm', models.PositiveIntegerField(default=40)),
                ('ancho_cm', models.PositiveIntegerField(default=30)),
                ('alto_cm', models.PositiveIntegerField(default=26)),
                ('carrier', models.CharField(max_length=40)),
                ('servicio', models.CharField(blank=True, max_length=60)),
                ('precio_cotizado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuera_de_meta', models.BooleanField(default=False, help_text="La mejor tarifa excede TORRE['TARIFA_OBJETIVO_MXN']")),
                ('ahorro_plan_mxn', models.DecimalField(decimal_places=2, default=0, help_text='Ahorro del plan completo vs enviar todo en un solo bulto (mismo valor en cada paquete del plan)', max_digits=10)),
                ('estado', models.CharField(choices=[('PLANEADO', 'Planeado'), ('EN_EMPAQUE', 'En empaque'), ('EMPACADO', 'Empacado'), ('DESPACHADO', 'Despachado')], db_index=True, default='PLANEADO', max_length=12)),
                ('peso_real_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'paquete',
                'ordering': ['pedido_id', 'numero'],
                'unique_together': {('pedido', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='guia',
            name='paquete',
            field=models.ForeignKey(blank=True, help_text='Paquete al que ampara esta guía; null en guías previas a la división de envíos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='envios.paquete'),
        ),
        migrations.CreateModel(
            name='PaqueteLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('linea_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_paquetes', to='pedidos.lineapedido')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='envios.paquete')),
            ],
            options={
                'verbose_name': 'línea de paquete',
                'verbose_name_plural': 'líneas de paquete',
            },
        ),
    ]
