# Generated by Django 5.2.16 on 2026-08-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_cotizacioncache_paquete_guia_paquete_paquetelinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetelinea',
            name='fraccion_de',
            field=models.PositiveIntegerField(default=1, help_text='>1 = la unidad de venta se reempacó: cantidad cuenta subunidades (ej. cantidad=1, fraccion_de=2 → media caja)'),
        ),
        migrations.AlterField(
            model_name='paquetelinea',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='Unidades de venta, o subunidades si fraccion_de > 1'),
        ),
    ]
