# Generated by Django 5.2.16 on 2026-08-07 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_paquetelinea_fraccion_de_alter_paquetelinea_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='etiquetas/%Y%m/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('IMPRESO', 'Impreso'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=10)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ts_impreso', models.DateTimeField(blank=True, null=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_impresion', to='envios.guia')),
            ],
            options={
                'verbose_name': 'trabajo de impresión',
                'verbose_name_plural': 'trabajos de impresión',
                'ordering': ['creado'],
            },
        ),
    ]
