# Generated by Django 5.2.17 on 2026-08-26 06:13

from django.db import migrations, models


def _backfill_proveedor(apps, schema_editor):
    """El AddField estampa 'envia' en todo; se corrigen mocks y flota local
    para que cancelar/rastrear ruteen con quien emitió cada guía."""
    Guia = apps.get_model("envios", "Guia")
    Guia.objects.filter(numero__startswith="MOCK-").update(proveedor="mock")
    Guia.objects.filter(carrier="local").update(proveedor="local")


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_trabajo_impresion_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='etiqueta_pdf',
            field=models.FileField(blank=True, help_text='PDF de la etiqueta cuando el proveedor la entrega en línea (no por URL)', null=True, upload_to='etiquetas/%Y%m/'),
        ),
        migrations.AddField(
            model_name='guia',
            name='proveedor',
            field=models.CharField(blank=True, default='envia', help_text='Integración que emitió la guía (envia / 99minutos / mock / local): cancelar y rastrear rutean por aquí', max_length=20),
        ),
        migrations.RunPython(_backfill_proveedor, migrations.RunPython.noop),
    ]
