# Generated by Django 5.2.17 on 2026-09-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0011_paquete_foto_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalidadCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=5, unique=True)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, help_text='code_2_digits de envia (CX, PU, QR)', max_length=2)),
                ('colonias', models.JSONField(blank=True, default=list)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'localidad por CP',
                'verbose_name_plural': 'localidades por CP',
            },
        ),
    ]
