# Generated by Django 5.2.17 on 2026-09-22 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0013_paquete_shopify_fulfillment_id'),
        ('pedidos', '0013_pedido_canal_suscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('carrier', models.CharField(max_length=40)),
                ('corral', models.CharField(blank=True, default='', max_length=20)),
                ('chofer', models.CharField(blank=True, default='', help_text='Nombre del chofer que firmó', max_length=120)),
                ('notas', models.CharField(blank=True, default='', max_length=300)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operador', models.ForeignKey(blank=True, help_text='Quien registró la salida en Torre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifiestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manifiesto de salida',
                'verbose_name_plural': 'manifiestos de salida',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='LineaManifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(blank=True, default='', max_length=64)),
                ('caja', models.PositiveIntegerField(blank=True, help_text='Número de caja dentro del pedido', null=True)),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_manifiesto', to='envios.guia')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_manifiesto', to='envios.paquete')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_manifiesto', to='pedidos.pedido')),
                ('manifiesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='envios.manifiesto')),
            ],
            options={
                'verbose_name': 'línea de manifiesto',
                'verbose_name_plural': 'líneas de manifiesto',
                'ordering': ['pedido_id', 'caja', 'pk'],
            },
        ),
    ]
