# Generated by Django 5.2.17 on 2026-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0014_manifiesto_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamanifiesto',
            name='sin_escaneo',
            field=models.BooleanField(default=False),
        ),
    ]
