# Generated by Django 5.2.17 on 2026-09-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0015_lineamanifiesto_sin_escaneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='estado',
            field=models.CharField(choices=[('GUIA_CREADA', 'Guía creada'), ('RECOLECTADO', 'Recolectado por el carrier'), ('EN_TRANSITO', 'En tránsito'), ('EN_RUTA', 'En ruta de entrega'), ('ENTREGADO', 'Entregado'), ('INTENTO_FALLIDO', 'Intento de entrega fallido'), ('RETENIDO', 'Retenido'), ('RETORNO', 'Retorno al remitente'), ('EXCEPCION', 'Excepción'), ('CANCELADA', 'Cancelada')], db_index=True, default='GUIA_CREADA', max_length=20),
        ),
    ]
