# Generated by Django 5.2.17 on 2026-09-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0016_cancelacion_y_cambio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='dias_promesa',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='estimado_entrega',
            field=models.CharField(blank=True, help_text='Promesa del carrier al cotizar ("2-4 días", "4 días · llega …")', max_length=60),
        ),
    ]
