# Generated by Django 5.2.17 on 2026-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0017_guia_compromiso_de_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='ts_recolectado_carrier',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
