# Generated by Django 5.2.17 on 2026-09-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0018_recolectado_por_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='sustituida_motivo',
            field=models.CharField(blank=True, choices=[('danada', 'Paquete dañado'), ('extraviada', 'Extraviado'), ('no_entregada', 'No entregado'), ('devolucion', 'Devolución del carrier'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='guia',
            name='ts_sustituida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
