# Generated by Django 5.2.17 on 2026-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0019_guia_sustituida'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='carrier_forzado',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
