# Generated by Django 5.2.17 on 2026-10-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0023_paquete_reingreso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='sustituida_motivo',
            field=models.CharField(blank=True, choices=[('danada', 'Paquete dañado'), ('extraviada', 'Extraviado'), ('no_entregada', 'No entregado'), ('devolucion', 'Devolución del carrier'), ('producto_erroneo', 'Producto erróneo'), ('otro', 'Otro')], max_length=20),
        ),
    ]
