# Generated by Django 5.2.17 on 2026-10-10 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_sku_shopify_variant_id'),
        ('envios', '0024_tipo_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='contenido_erroneo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquetelinea',
            name='sku_real',
            field=models.ForeignKey(blank=True, help_text='Producto que salió en lugar del pedido (producto erróneo)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajo_en_lugar_de', to='catalogo.sku'),
        ),
    ]
