# Generated by Django 5.2.16 on 2026-07-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_idempotencia', models.CharField(max_length=200, unique=True)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('consola', 'Consola')], max_length=10)),
                ('destinatario', models.CharField(max_length=120)),
                ('cuerpo', models.TextField()),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('plantilla_clave', models.CharField(blank=True, max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=60)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='core.cliente')),
            ],
            options={
                'verbose_name': 'notificación enviada',
                'verbose_name_plural': 'notificaciones enviadas',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('A', 'A — Confirmación de pedido'), ('B', 'B — En camino (solo al RECOLECTADO)'), ('E', 'E — Retraso')], max_length=1)),
                ('nombre', models.CharField(max_length=120)),
                ('cuerpo', models.TextField(help_text='Variables: {nombre}, {folio}, {guia}, {link_rastreo}, {fecha}, {marca}, {corte}')),
                ('aprobada_por_cliente', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Vacío = plantilla default para todos los clientes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_mensaje', to='core.cliente')),
            ],
            options={
                'verbose_name': 'plantilla de mensaje',
                'verbose_name_plural': 'plantillas de mensaje',
                'ordering': ['clave', 'cliente__nombre'],
                'constraints': [models.UniqueConstraint(fields=('clave', 'cliente'), name='plantilla_unica_por_cliente'), models.UniqueConstraint(condition=models.Q(('cliente__isnull', True)), fields=('clave',), name='plantilla_default_unica')],
            },
        ),
    ]
