# Generated by Django 5.2.16 on 2026-08-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_suscripcion_push_webpush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcionpush',
            name='endpoint',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
