# Generated by Django 5.2.16 on 2026-07-22 00:31

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('contacto_nombre', models.CharField(blank=True, max_length=120)),
                ('contacto_whatsapp', models.CharField(blank=True, max_length=20)),
                ('buffer_stock', models.PositiveIntegerField(default=0, help_text='Buffer restado del disponible publicado')),
                ('carrier_preferente', models.CharField(default='paquetexpress', max_length=40)),
                ('naked_packing_local', models.BooleanField(default=True)),
                ('guia_de_voz', models.TextField(blank=True, help_text='Reglas de tono para mensajes al comprador final')),
                ('umbral_visto_bueno_mxn', models.DecimalField(decimal_places=2, default=2000, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(db_index=True, max_length=30)),
                ('entidad_id', models.CharField(db_index=True, max_length=60)),
                ('tipo', models.CharField(blank=True, max_length=30)),
                ('archivo', models.FileField(upload_to=apps.core.models._ruta_evidencia)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('tomada_por', models.CharField(blank=True, max_length=120)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('congelada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_tipo', models.CharField(default='sistema', max_length=10)),
                ('actor_id', models.CharField(blank=True, max_length=120)),
                ('entidad', models.CharField(db_index=True, max_length=60)),
                ('entidad_id', models.CharField(db_index=True, max_length=60)),
                ('accion', models.CharField(max_length=60)),
                ('delta', models.JSONField(blank=True, default=dict)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'eventos de auditoría',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('portal', 'Cliente (portal)'), ('piso', 'Operador de piso'), ('mesa', 'Mesa de Control')], max_length=10)),
                ('pin', models.CharField(blank=True, help_text='PIN de firma para ajustes (piso/mesa)', max_length=6)),
                ('cliente', models.ForeignKey(blank=True, help_text='Obligatorio para rol portal; vacío para piso/mesa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.cliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
