# Generated by Django 5.2.16 on 2026-08-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='branding',
            field=models.JSONField(blank=True, default=dict, help_text='Identidad para páginas públicas de rastreo: color_primario, color_fondo, logo_url, nombre_publico, whatsapp_soporte, dominio_tienda'),
        ),
    ]
