# Generated by Django 5.2.16 on 2026-08-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tarifario',
            field=models.JSONField(blank=True, default=dict, help_text="Override del tarifario (settings.TORRE['TARIFARIO_DEFAULT']): almacenaje_mes, alistamiento_pedido, empaque_pedido, bloque_kg, envio_bloque {local, metro, nacional}. Vacío = tarifario default."),
        ),
    ]
