# Generated by Django 5.2.17 on 2026-08-11 09:24

from django.contrib.auth.hashers import identify_hasher, make_password
from django.db import migrations, models


def hashear_pines_existentes(apps, schema_editor):
    """Los PINs guardados en claro (deuda del arranque) se hashean en sitio.

    El modelo histórico no trae los métodos del modelo real, así que la lógica
    se replica aquí: si el valor no es un hash reconocible, se hashea.
    """
    PerfilUsuario = apps.get_model("core", "PerfilUsuario")
    for perfil in PerfilUsuario.objects.exclude(pin=""):
        try:
            identify_hasher(perfil.pin)
        except ValueError:
            perfil.pin = make_password(str(perfil.pin))
            perfil.save(update_fields=["pin"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_tarifario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN de firma para ajustes (piso/mesa) — se guarda hasheado', max_length=128),
        ),
        # Irreversible a propósito: de un hash no se regresa al PIN en claro.
        migrations.RunPython(hashear_pines_existentes, migrations.RunPython.noop),
    ]
