# Generated by Django 5.2.17 on 2026-09-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_incidencias_auto_pausadas_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='branding',
            field=models.JSONField(blank=True, default=dict, help_text='Identidad para páginas públicas de rastreo: color_primario, color_fondo, logo_url, nombre_publico, whatsapp_soporte, dominio_tienda, lema, pie'),
        ),
    ]
