# Generated by Django 5.2.17 on 2026-09-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_branding_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='avisos_comprador',
            field=models.BooleanField(default=False, help_text='Torre le escribe al comprador final (WhatsApp: confirmación, en camino, retraso). Apagado cuando la tienda ya lo hace (Shopify); préndelo para un cliente fuera de Shopify.'),
        ),
    ]
