# Generated by Django 5.2.17 on 2026-10-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_avisos_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='facturacion_desde',
            field=models.DateField(blank=True, help_text='Día desde el que se cobra almacenaje (prorrateado en su primer corte). Vacío = el día de su primer pedido.', null=True),
        ),
    ]
