# Generated by Django 5.2.17 on 2026-10-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente_facturacion_desde'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='carrier_respaldo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
