# Generated by Django 5.2.16 on 2026-07-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('shopify', 'Shopify')], default='shopify', max_length=20)),
                ('dominio', models.CharField(help_text='p. ej. colima-mx.myshopify.com', max_length=120, unique=True)),
                ('token', models.CharField(blank=True, help_text='Access token de la custom app. Vacío = modo mock (dev).', max_length=200)),
                ('location_id', models.CharField(blank=True, help_text='Location de Shopify que operamos (id numérico o GID)', max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('checkpoint_reconciliacion', models.DateTimeField(blank=True, help_text='Última reconciliación de pedidos (updated_at_min del siguiente polling)', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='core.cliente')),
            ],
            options={
                'verbose_name': 'tienda',
                'ordering': ['cliente__nombre', 'dominio'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('ingesta', 'Ingesta'), ('push', 'Push')], max_length=10)),
                ('resultado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=10)),
                ('detalle', models.TextField(blank=True)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integraciones.tienda')),
            ],
            options={
                'verbose_name': 'log de sincronización',
                'verbose_name_plural': 'logs de sincronización',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=120, unique=True)),
                ('topic', models.CharField(db_index=True, max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('procesado', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('webhook', 'Webhook'), ('reconciliacion', 'Reconciliación'), ('manual', 'Manual')], default='webhook', max_length=15)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integraciones.tienda')),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='PushInventarioPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes_pendientes', to='catalogo.sku')),
            ],
            options={
                'verbose_name': 'push de inventario pendiente',
                'verbose_name_plural': 'pushes de inventario pendientes',
                'ordering': ['creado'],
                'constraints': [models.UniqueConstraint(fields=('sku',), name='push_pendiente_sku_unico')],
            },
        ),
    ]
