# Generated by Django 5.2.17 on 2026-08-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text="Secreto con el que Shopify FIRMA los webhooks — el 'signing secret' de Configuración → Notificaciones o el API secret key de la app. NO es el access token: Shopify jamás firma con el shpat_. Vacío = webhooks rechazados en producción.", max_length=200),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='token',
            field=models.CharField(blank=True, help_text='Access token (shpat_…) de la custom app para la Admin API. Vacío = modo mock (dev).', max_length=200),
        ),
    ]
