# Generated by Django 5.2.17 on 2026-09-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0002_tienda_webhook_secret'),
        ('pedidos', '0018_lineapedido_reposicion_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrituraShopifyPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=160, unique=True)),
                ('accion', models.CharField(choices=[('fulfillment', 'Crear fulfillment'), ('tracking', 'Actualizar rastreo (reposición)'), ('evento', 'Evento de avance')], max_length=20)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('intentos', models.PositiveIntegerField(default=1)),
                ('ultimo_error', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultimo_intento', models.DateTimeField(auto_now=True)),
                ('vence', models.DateTimeField(db_index=True, help_text='Después de esta hora el cron ya no la reintenta; Mesa puede reactivarla.')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrituras_shopify_pendientes', to='pedidos.pedido')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrituras_pendientes', to='integraciones.tienda')),
            ],
            options={
                'verbose_name': 'escritura a Shopify pendiente',
                'verbose_name_plural': 'escrituras a Shopify pendientes',
                'ordering': ['creado'],
            },
        ),
    ]
