# Generated by Django 5.2.16 on 2026-08-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_paquetelinea_fraccion_de_alter_paquetelinea_cantidad'),
        ('rastreo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=12, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('guia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_etiqueta', to='envios.guia')),
            ],
            options={
                'verbose_name': 'acceso de etiqueta',
                'verbose_name_plural': 'accesos de etiqueta',
                'ordering': ['-creado'],
            },
        ),
    ]
