# Generated by Django 5.2.17 on 2026-10-01 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_cliente_avisos_comprador'),
        ('envios', '0020_paquete_carrier_forzado'),
        ('incidencias', '0007_compensacion_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReembolsoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='MXN sin IVA: lo que se le descuenta al cliente', max_digits=10)),
                ('fecha', models.DateTimeField(db_index=True, help_text='Cuándo nos reembolsó la paquetería (o se canceló la guía): decide el corte')),
                ('origen', models.CharField(choices=[('cancelacion', 'Guía cancelada'), ('reclamacion', 'Reclamación pagada'), ('ajuste', 'Ajuste manual')], default='ajuste', max_length=12)),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('registrado_por', models.CharField(blank=True, default='', max_length=80)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos_guia', to='core.cliente')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='envios.guia')),
                ('incidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_guia', to='incidencias.incidencia')),
            ],
            options={
                'verbose_name': 'reembolso de guía',
                'verbose_name_plural': 'reembolsos de guía',
                'ordering': ['fecha', 'pk'],
            },
        ),
    ]
