# Generated by Django 5.2.16 on 2026-07-22 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('contador', models.CharField(max_length=120)),
                ('esperado', models.PositiveIntegerField()),
                ('contado', models.PositiveIntegerField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='catalogo.sku')),
            ],
            options={
                'verbose_name': 'conteo',
                'verbose_name_plural': 'conteos',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('delta', models.IntegerField(help_text='Con signo: negativo quita, positivo agrega')),
                ('motivo', models.CharField(choices=[('conteo', 'Diferencia detectada en conteo'), ('dano_bodega', 'Daño en bodega'), ('caducidad', 'Producto caducado'), ('merma_operativa', 'Merma operativa'), ('error_recepcion', 'Corrección de recepción'), ('robo_extravio', 'Robo o extravío'), ('reconciliacion', 'Reconciliación con cliente')], max_length=20)),
                ('autorizo_1', models.CharField(help_text='Primera firma (username)', max_length=120)),
                ('autorizo_2', models.CharField(help_text='Segunda firma (username, distinta)', max_length=120)),
                ('incidencia_ref', models.CharField(blank=True, help_text='Folio INC-AAAA-#### si aplica', max_length=20)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='catalogo.lote')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='catalogo.sku')),
                ('conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='inventario.conteo')),
            ],
            options={
                'verbose_name': 'ajuste',
                'verbose_name_plural': 'ajustes',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='OrdenEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('ANUNCIADA', 'Anunciada'), ('EN_RECEPCION', 'En recepción'), ('RECIBIDA', 'Recibida'), ('CERRADA', 'Cerrada (todo vendible)')], default='ANUNCIADA', max_length=15)),
                ('fecha_compromiso', models.DateField(blank=True, help_text='Cita de llegada (mar/jue)', null=True)),
                ('ts_descarga_fin', models.DateTimeField(blank=True, null=True)),
                ('ts_vendible', models.DateTimeField(blank=True, help_text='Cuándo quedó todo ubicado', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_entrada', to='core.cliente')),
            ],
            options={
                'verbose_name': 'orden de entrada (ASN)',
                'verbose_name_plural': 'órdenes de entrada (ASN)',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='LineaASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anunciada', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('cantidad_danada', models.PositiveIntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_asn', to='catalogo.sku')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.ordenentrada')),
            ],
            options={
                'verbose_name': 'línea de ASN',
                'verbose_name_plural': 'líneas de ASN',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepción'), ('putaway', 'Put-away'), ('reserva', 'Reserva'), ('pick', 'Pick'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('retorno', 'Retorno'), ('merma', 'Merma'), ('conteo', 'Conteo')], max_length=12)),
                ('delta', models.IntegerField(help_text='Cantidad con signo: negativo = sale físico')),
                ('estado_origen', models.CharField(blank=True, max_length=20)),
                ('estado_destino', models.CharField(blank=True, max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='PED-x / ASN-x / AJU-x / CON-x', max_length=40)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.lote')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.sku')),
            ],
            options={
                'verbose_name': 'movimiento (kardex)',
                'verbose_name_plural': 'movimientos (kardex)',
                'ordering': ['-ts', '-id'],
                'indexes': [models.Index(fields=['sku', 'ts'], name='inventario__sku_id_da4fc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_putaway', 'En put-away (recibido sin ubicar)'), ('ubicado_vendible', 'Ubicado vendible'), ('reservado', 'Reservado (capa sobre vendible)'), ('en_empaque', 'En empaque'), ('cuarentena', 'Cuarentena')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='catalogo.lote')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='catalogo.sku')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='catalogo.ubicacion')),
            ],
            options={
                'verbose_name': 'saldo',
                'verbose_name_plural': 'saldos',
                'ordering': ['sku', 'ubicacion'],
                'unique_together': {('sku', 'ubicacion', 'lote', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='TareaConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='inventario.conteo')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_conteo', to='catalogo.sku')),
            ],
            options={
                'verbose_name': 'tarea de conteo',
                'verbose_name_plural': 'tareas de conteo',
                'ordering': ['-fecha', 'sku__codigo'],
                'unique_together': {('fecha', 'sku')},
            },
        ),
    ]
