# Generated by Django 5.2.16 on 2026-08-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenentrada',
            name='tarimas',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tarimas anunciadas por el cliente'),
        ),
        migrations.AddField(
            model_name='ordenentrada',
            name='tarimas_recibidas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
