# Generated by Django 5.2.17 on 2026-09-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_tarimas_asn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuste',
            name='motivo',
            field=models.CharField(choices=[('conteo', 'Diferencia detectada en conteo'), ('dano_bodega', 'Daño en bodega'), ('caducidad', 'Producto caducado'), ('merma_operativa', 'Merma operativa'), ('error_recepcion', 'Corrección de recepción'), ('robo_extravio', 'Robo o extravío'), ('reconciliacion', 'Reconciliación con cliente'), ('reconciliacion_inv', 'Reconciliación de inventario')], max_length=20),
        ),
    ]
