# Generated by Django 5.2.17 on 2026-09-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_ajuste_motivo_reconciliacion_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaasn',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineaasn',
            name='lote_codigo',
            field=models.CharField(blank=True, default='', help_text='Lote anunciado por el cliente; el piso lo ve preseleccionado al ubicar', max_length=60),
        ),
    ]
