# Generated by Django 5.2.17 on 2026-09-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_linea_asn_lote'),
        ('pedidos', '0006_reingreso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenentrada',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reingresos', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='ordenentrada',
            name='tipo',
            field=models.CharField(choices=[('asn', 'ASN del cliente'), ('reingreso', 'Reingreso de pedido')], default='asn', max_length=10),
        ),
    ]
