# Generated by Django 5.2.17 on 2026-10-06 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_cliente_facturacion_desde'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoIncidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Vacío = recibe las incidencias de todos los clientes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correos_incidencias', to='core.cliente')),
            ],
            options={
                'verbose_name': 'correo de incidencias',
                'verbose_name_plural': 'correos de incidencias',
                'ordering': ['cliente__nombre', 'correo'],
                'constraints': [models.UniqueConstraint(fields=('correo', 'cliente'), name='correoincidencias_unico_por_cliente')],
            },
        ),
    ]
