# Generated by Django 5.2.16 on 2026-07-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. A-01-2, REC-01, SAL-PQX', max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepción'), ('picking', 'Picking'), ('reserva', 'Reserva'), ('merma', 'Merma'), ('retorno', 'Retorno'), ('salida', 'Salida (corral)')], max_length=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('codigo_barras', models.CharField(blank=True, max_length=64)),
                ('descripcion', models.CharField(max_length=200)),
                ('peso_gr', models.PositiveIntegerField(default=0, help_text='Peso unitario en gramos')),
                ('largo_cm', models.PositiveIntegerField(default=0)),
                ('ancho_cm', models.PositiveIntegerField(default=0)),
                ('alto_cm', models.PositiveIntegerField(default=0)),
                ('requiere_lote', models.BooleanField(default=True)),
                ('unidad', models.CharField(default='pieza', max_length=20)),
                ('precio_declarado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('punto_reorden', models.PositiveIntegerField(default=0)),
                ('backorder_habilitado', models.BooleanField(default=False)),
                ('fecha_resurtido', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='core.cliente')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
                'ordering': ['cliente', 'codigo'],
                'unique_together': {('cliente', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='catalogo.sku')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['fecha_caducidad', 'codigo'],
                'unique_together': {('sku', 'codigo')},
            },
        ),
    ]
