# Generated by Django 5.2.16 on 2026-08-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='empaques_divisibles',
            field=models.PositiveIntegerField(default=1, help_text='En cuántas cajas puede reempacarse una unidad de venta para abaratar el envío (ej. caja de 24 → 2 medias de 12). 1 = indivisible.'),
        ),
    ]
