# Generated by Django 5.2.17 on 2026-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='variante',
            field=models.CharField(blank=True, default='', help_text='Sabor/tamaño/presentación cuando el producto tiene variantes (ej. 500 g); vacío si no', max_length=100),
        ),
    ]
