# Generated by Django 5.2.17 on 2026-08-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_sku_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='es_kit',
            field=models.BooleanField(default=False, help_text='Se arma al empacar (TeaBox): no reserva stock propio ni publica inventario; su contenido se declara en empaque o llega en la orden'),
        ),
    ]
