# Generated by Django 5.2.17 on 2026-09-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_ubicacion_lleno_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='este_lado_arriba',
            field=models.BooleanField(default=False, help_text='Imprime ESTE LADO ARRIBA en la etiqueta de la caja'),
        ),
        migrations.AddField(
            model_name='sku',
            name='fragil',
            field=models.BooleanField(default=False, help_text='Imprime FRÁGIL en la etiqueta de la caja'),
        ),
    ]
