# Generated by Django 5.2.17 on 2026-10-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_sku_fragil_este_lado_arriba'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='shopify_variant_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
